// import type { NextPage } from 'next'
import React from 'react';
import Head from 'next/head'
import Image from 'next/image'

export default function Page() {
  return (
    <div>
      <Head>
        <title>オクモト看板</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>about</h1>
      </main>

    </div>
  )
}
